<a href="https://colab.research.google.com/github/chandupradeep18/Python_pandas/blob/main/Accessing_and_sorting_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
parquet=pd.read_parquet('/content/drive/MyDrive/Data Sources/results.parquet')

In [ ]:
parquet.columns

Index(['year', 'type', 'discipline', 'event', 'as', 'athlete_id', 'noc',
       'team', 'place', 'tied', 'medal'],
      dtype='object')

In [ ]:
print(parquet.head())
print(parquet.tail())
print(parquet.sample(5))

     year    type discipline                     event                     as  \
0  1912.0  Summer     Tennis    Singles, Men (Olympic)  Jean-François Blanchy
1  1912.0  Summer     Tennis    Doubles, Men (Olympic)  Jean-François Blanchy
2  1920.0  Summer     Tennis    Singles, Men (Olympic)  Jean-François Blanchy
3  1920.0  Summer     Tennis  Doubles, Mixed (Olympic)  Jean-François Blanchy
4  1920.0  Summer     Tennis    Doubles, Men (Olympic)  Jean-François Blanchy

   athlete_id  noc             team  place   tied medal
0           1  FRA             None   17.0   True  None
1           1  FRA   Jean Montariol    NaN  False  None
2           1  FRA             None   32.0   True  None
3           1  FRA  Jeanne Vaussard    8.0   True  None
4           1  FRA  Jacques Brugnon    4.0  False  None
          year    type              discipline                          event  \
308403  2022.0  Winter                    Luge         Singles, Men (Olympic)
308404  2022.0  Winter  Alpine Skiing (Skiing)        Slalom, Women (Olympic)
308405  2022.0  Winter  Alpine Skiing (Skiing)          Team, Mixed (Olympic)
308406  2022.0  Winter  Alpine Skiing (Skiing)  Giant Slalom, Women (Olympic)
308407  2022.0  Winter                    None        Slalom, Women (Olympic)

                          as  athlete_id   noc    team  place   tied medal
308403         Marián Skupek      148983   SVK    None   26.0  False  None
308404         Elsa Fermbäck      148984   SWE    None   28.0  False  None
308405         Hilma Lövblom      148985   SWE  Sweden   13.0  False  None
308406         Hilma Lövblom      148985   SWE    None    NaN  False  None
308407  Charlotta Säfvenberg      148986  None    None   24.0  False  None
          year    type                 discipline  \
174213  1992.0  Winter  Freestyle Skiing (Skiing)
73891   1992.0  Summer                   Handball
6691    1972.0  Summer                     Boxing
218919  2002.0  Winter                   Biathlon
6972    1928.0  Summer                     Boxing

                                       event                   as  athlete_id  \
174213  Aerials, Women (Olympic (non-medal))  Nataliya Sherstneva       82368
73891                Handball, Men (Olympic)        Hendrik Ochel       32102
6691              Lightweight, Men (Olympic)         Neville Cole        3376
218919        15 kilometres, Women (Olympic)        Kong Yingchao      101176
6972             Middleweight, Men (Olympic)      Albert Leidmann        3624

        noc     team  place   tied medal
174213  EUN     None    9.0  False  None
73891   GER  Germany   10.0  False  None
6691    GBR     None   17.0   True  None
218919  CHN     None   44.0  False  None
6972    GER     None    9.0   True  None

In [ ]:
print(parquet.loc[9018])
print(parquet.loc[9018,'type'])
print(parquet.loc[9018,['type', 'discipline', 'event']])
#update Row Value
print(parquet.loc[9018,'discipline'])
parquet.loc[9018,'discipline']='Swimming'
print(parquet.loc[9018,'discipline'])

year                               1984.0
type                               Summer
discipline        Basketball (Basketball)
event         Basketball, Women (Olympic)
as                    Biljana Majstorović
athlete_id                           5354
noc                                   YUG
team                           Yugoslavia
place                                 6.0
tied                                False
medal                                None
Name: 9018, dtype: object
Summer
type                               Summer
discipline        Basketball (Basketball)
event         Basketball, Women (Olympic)
Name: 9018, dtype: object
Basketball (Basketball)
Swimming

In [ ]:
print(parquet.iloc[9018])
print(parquet.iloc[9018,5])
print(parquet.iloc[9018,[4,5,6,7]])
#update Row Value
print(parquet.iloc[9018,2])
parquet.iloc[9018,2]='Basketball'
print(parquet.iloc[9018,2])

year                               1984.0
type                               Summer
discipline                       Swimming
event         Basketball, Women (Olympic)
as                    Biljana Majstorović
athlete_id                           5354
noc                                   YUG
team                           Yugoslavia
place                                 6.0
tied                                False
medal                                None
Name: 9018, dtype: object
5354
as            Biljana Majstorović
athlete_id                   5354
noc                           YUG
team                   Yugoslavia
Name: 9018, dtype: object
Swimming
Basketball

In [ ]:
print(parquet.at[3618,'event'])
print(parquet.iat[3618,1])

Light-Flyweight, Men (Olympic)
Summer

In [ ]:
#Sorting Data
parquet.sort_values(['year','athlete_id'],ascending=False)

In [ ]:
for index,row in parquet.iterrows():
  print(index)
  print(row)
  if index>5:
    break

0
year                          1912.0
type                          Summer
discipline                    Tennis
event         Singles, Men (Olympic)
as             Jean-François Blanchy
athlete_id                         1
noc                              FRA
team                            None
place                           17.0
tied                            True
medal                           None
Name: 0, dtype: object
1
year                          1912.0
type                          Summer
discipline                    Tennis
event         Doubles, Men (Olympic)
as             Jean-François Blanchy
athlete_id                         1
noc                              FRA
team                  Jean Montariol
place                            NaN
tied                           False
medal                           None
Name: 1, dtype: object
2
year                          1920.0
type                          Summer
discipline                    Tennis
event         Singles, Men (Olympic)
as             Jean-François Blanchy
athlete_id                         1
noc                              FRA
team                            None
place                           32.0
tied                            True
medal                           None
Name: 2, dtype: object
3
year                            1920.0
type                            Summer
discipline                      Tennis
event         Doubles, Mixed (Olympic)
as               Jean-François Blanchy
athlete_id                           1
noc                                FRA
team                   Jeanne Vaussard
place                              8.0
tied                              True
medal                             None
Name: 3, dtype: object
4
year                          1920.0
type                          Summer
discipline                    Tennis
event         Doubles, Men (Olympic)
as             Jean-François Blanchy
athlete_id                         1
noc                              FRA
team                 Jacques Brugnon
place                            4.0
tied                           False
medal                           None
Name: 4, dtype: object
5
year                          1996.0
type                          Summer
discipline                    Tennis
event         Singles, Men (Olympic)
as                    Arnaud Boetsch
athlete_id                         2
noc                              FRA
team                            None
place                           17.0
tied                            True
medal                           None
Name: 5, dtype: object
6
year                          1996.0
type                          Summer
discipline                    Tennis
event         Doubles, Men (Olympic)
as                    Arnaud Boetsch
athlete_id                         2
noc                              FRA
team                 Guillaume Raoux
place                           17.0
tied                            True
medal                           None
Name: 6, dtype: object

In [ ]:
#filtering Data Using Conditions
parquet.loc[parquet['tied']==False]
parquet.loc[(parquet['place']==2) & (parquet['year'].between(1981, 1984)) | (parquet['type']=='Summer')]
parquet.loc[(parquet['event'].str.contains("Men")) & (parquet['event'].str.contains("Singles")) & (parquet['year'].between(1981, 1990)) & (parquet['place']==2) & (parquet['type']=='Summer') ]
parquet.loc[(parquet['place'].isin([4,5,6])) & (parquet['year'].between(1998,2026)) & (parquet['type']=='Summer') & (parquet['discipline']=='Athletics') & (parquet['event'].str.contains("Men"))]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
120538,2000.0,Summer,Athletics,"400 metres, Men (Olympic)",Gustavo Aguirre,55041,ARG,None,5.0,False,None
133934,2004.0,Summer,Athletics,"400 metres, Men (Olympic)",Adem Hecini,64295,ALG,None,5.0,False,None
134241,2000.0,Summer,Athletics,"200 metres, Men (Olympic)",Carlos Gats,64422,ARG,None,5.0,False,None
135117,2000.0,Summer,Athletics,"400 metres Hurdles, Men (Olympic)",Rohan Robinson,64784,AUS,None,4.0,False,None
135438,2000.0,Summer,Athletics,"200 metres, Men (Olympic)",Martin Lachkovics,64917,AUT,None,4.0,False,None
...,...,...,...,...,...,...,...,...,...,...,...
305904,2020.0,Summer,Athletics,"400 metres, Men (Olympic)",Michael Cherry,147341,USA,None,4.0,False,None
305906,2020.0,Summer,Athletics,"400 metres, Men (Olympic)",Michael Norman,147342,USA,None,5.0,False,None
305913,2020.0,Summer,Athletics,"400 metres, Men (Olympic)",Randolph Ross,147347,USA,None,4.0,False,None
305916,2020.0,Summer,Athletics,"100 metres, Men (Olympic)",Ronnie Baker,147349,USA,None,5.0,False,None
305917,2020.0,Summer,Athletics,"4 × 100 metres Relay, Men (Olympic)",Ronnie Baker,147349,USA,United States,6.0,False,None

In [ ]:
#Adding and Removing Columns
parquet['Details']=parquet['type']+" - "+parquet['discipline']
parquet.sample(20)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,Details
269239,2012.0,Summer,Athletics,"400 metres, Men (Olympic)",Deon Lendore,125966,TTO,None,5.0,False,None,Summer - Athletics
165970,1968.0,Summer,Athletics,"80 metres Hurdles, Women (Olympic)",Marijana Lubej,79362,YUG,None,5.0,False,None,Summer - Athletics
66059,1976.0,Summer,Artistic Gymnastics (Gymnastics),"Pommelled Horse, Men (Olympic)",Hiroshi Kajiyama,30589,JPN,None,7.0,False,None,Summer - Artistic Gymnastics (Gymnastics)
182132,1948.0,Winter,Alpine Skiing (Skiing),"Downhill, Men (Olympic)",Marius Eriksen,85543,NOR,None,20.0,False,None,Winter - Alpine Skiing (Skiing)
301772,2020.0,Summer,Athletics,"4 × 400 metres Relay, Mixed (Olympic)",Sophie Becker,143848,IRL,Ireland,8.0,False,None,Summer - Athletics
5444,1912.0,Summer,Tennis,"Doubles, Covered Courts, Men (Olympic)",Carl Kempe,2621,SWE,Gunnar Setterwall,2.0,False,Silver,Summer - Tennis
174558,1964.0,Winter,Cross Country Skiing (Skiing),"3 × 5 kilometres Relay, Women (Olympic)",Krastana Stoeva,82469,BUL,Bulgaria,5.0,False,None,Winter - Cross Country Skiing (Skiing)
140482,2000.0,Summer,Athletics,"4 × 400 metres Relay, Men (Olympic)",Íñigo Monreal,67264,ESP,Spain,5.0,False,None,Summer - Athletics
276482,2020.0,Summer,Football (Football),"Football, Women (Olympic)",Steph Catley,129004,AUS,Australia,4.0,False,None,Summer - Football (Football)
250195,2008.0,Summer,Weightlifting,"Light-Heavyweight, Men (Olympic)",Benedict Uloko,116385,NGR,None,10.0,False,None,Summer - Weightlifting
183345,1956.0,Winter,Alpine Skiing (Skiing),"Downhill, Men (Olympic)",Ibrahim Geagea,85990,LBN,None,42.0,False,None,Winter - Alpine Skiing (Skiing)
8299,1960.0,Summer,Boxing,"Featherweight, Men (Olympic)",Joe Okezie,4795,NGR,None,17.0,True,None,Summer - Boxing
292323,2018.0,Winter,Speed Skating (Skating),"1,000 metres, Women (Olympic)",Karolina Bosiek,137926,POL,None,29.0,False,None,Winter - Speed Skating (Skating)
271881,2014.0,Winter,Freestyle Skiing (Skiing),"Halfpipe, Women (Olympic)",Katrien Aerts,127393,BEL,None,17.0,False,None,Winter - Freestyle Skiing (Skiing)
299187,2020.0,Summer,Diving (Aquatics),"Synchronized Platform, Women (Olympic)",Zhang Jiaqi,141674,CHN,Chen Yuxi,1.0,False,Gold,Summer - Diving (Aquatics)
219946,2002.0,Winter,Short Track Speed Skating (Skating),"3,000 metres Relay, Women (Olympic)",Christin Priebst,101411,GER,Germany,8.0,False,None,Winter - Short Track Speed Skating (Skating)
114936,1996.0,Summer,Swimming (Aquatics),"4 × 100 metres Medley Relay, Men (Olympic)",Tripp Schwenk,51558,USA,United States,1.0,False,Gold,Summer - Swimming (Aquatics)
151039,1996.0,Summer,Athletics,"4 × 100 metres Relay, Men (Olympic)",Willis Todman,72194,IVB,British Virgin Islands,7.0,False,None,Summer - Athletics
28988,1996.0,Summer,Cycling Road (Cycling),"Road Race, Individual, Men (Olympic)",Omar Ochoa,15920,GUA,None,NaN,False,None,Summer - Cycling Road (Cycling)
278665,2016.0,Summer,Swimming (Aquatics),"200 metres Breaststroke, Women (Olympic)",Chloé Tutton,130281,GBR,None,4.0,False,None,Summer - Swimming (Aquatics)

In [ ]:
parquet.drop(columns=['Details'],inplace=True)

In [ ]:
parquet

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,None,26.0,False,None
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,None,28.0,False,None
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,None
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,None,NaN,False,None
308407,2022.0,Winter,None,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,None,None,24.0,False,None