<a href="https://colab.research.google.com/github/chandupradeep18/Python_pandas/blob/main/Adding_and_Removing_columns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [23]:
current_date = pd.Timestamp.now()
amazon_sales=pd.read_csv('/content/drive/MyDrive/Data Sources/amazon_sales.csv')
amazon_sales.sample(10)
bios=pd.read_csv('/content/drive/MyDrive/Data Sources/bios.csv')
bios.sample(10)
olympics=pd.read_parquet('/content/drive/MyDrive/Data Sources/results.parquet')
olympics.sample(10)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
26211,1976.0,Summer,Cycling Road (Cycling),"Road Race, Individual, Men (Olympic)",Víctor González,14533,URU,None,NaN,False,None
7806,1952.0,Summer,Boxing,"Flyweight, Men (Olympic)",Han Su-An,4352,KOR,None,5.0,True,None
242196,2012.0,Summer,Artistic Gymnastics (Gymnastics),"Parallel Bars, Men (Olympic)",Sergio Muñoz,111955,ESP,None,55.0,False,None
129211,2016.0,Summer,Sailing,"Windsurfer, Women (Olympic)",Gelly Skarlatou,61050,GRE,None,19.0,False,None
172888,1980.0,Winter,Luge,"Singles, Women (Olympic)",Anneli Näsström,81964,SWE,None,19.0,False,None
109391,1952.0,Summer,Swimming (Aquatics),"400 metres Freestyle, Men (Olympic)",Roar Woldum,49575,NOR,None,42.0,False,None
216170,1998.0,Winter,Cross Country Skiing (Skiing),"4 × 10 kilometres Relay, Men (Olympic)",Guido Visser,100088,CAN,Canada,18.0,False,None
304719,2020.0,Summer,Football (Football),"Football, Men (Olympic)",Valentin Gheorghe,146350,ROU,Romania,11.0,False,None
118290,1952.0,Summer,Water Polo (Aquatics),"Water Polo, Men (Olympic)",Taha El-Gamal,53713,EGY,Egypt,9.0,True,None
198675,2004.0,Summer,Shooting,"Small-Bore Rifle, Three Positions, 50 metres, ...",Marco De Nicolo,93085,ITA,None,31.0,True,None

In [32]:
#Adding New Column to Data Frame
bios['first_name']=bios['name'].str.split(' ').str[0]
bios['last_name']=bios['name'].str.split(' ').str[1]
bios['status']=np.where(bios['died_date'].isna(),'Alive','Died')
bios['Note']=np.where(bios['height_cm'].isna(),'Height is Required','')
bios.sample(5)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,age,first_name,last_name,status,Note
88604,89313,Alastair Gordon,1976-12-08,Sydney,New South Wales,AUS,Australia,193.0,91.0,NaT,49.618070,Alastair,Gordon,Alive,
47769,48121,Éva Miklósfalvy,1959-12-10,Budapest,Budapest,HUN,Hungary,173.0,66.0,NaT,66.614648,Éva,Miklósfalvy,Alive,
119443,121255,Uno Sanli,1989-01-05,Eskilstuna,Södermanland,SWE,Sweden,172.0,58.0,NaT,37.541410,Uno,Sanli,Alive,
32226,32468,Kristine Duvholt Havnas,1974-01-31,Tønsberg,Vestfold og Telemark,NOR,Norway,166.0,64.0,NaT,52.470910,Kristine,Duvholt,Alive,
91597,92326,Miklós Illyés,1972-06-12,Miskolc,Borsod-Abaúj-Zemplén,HUN,Hungary,169.0,73.0,NaT,54.108145,Miklós,Illyés,Alive,

In [36]:
#Removing a Columns from DataFrame
bios.drop(columns=['Note'],inplace=True)
bios.sample(10)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,age,first_name,last_name,status
135779,138993,Erik Engel,2002-11-10,Hallein,Salzburg,AUT,Austria,183.0,71.0,NaT,23.696099,Erik,Engel,Alive
26856,27051,Abdullah Basheer Al-Abdullah,1971-09-17,NaN,NaN,NaN,Qatar,NaN,NaN,NaT,54.844627,Abdullah,Basheer,Alive
124588,126896,Louisa Sawers-Gurski,1988-05-26,Chertsey,England,GBR,Great Britain,176.0,70.0,NaT,38.154689,Louisa,Sawers-Gurski,Alive
104186,105196,Apostolos Papandreou,1975-11-10,Athina (Athens),Attiki,GRE,Greece,184.0,90.0,NaT,50.696783,Apostolos,Papandreou,Alive
86623,87315,Kazuaki Ichimura,1957-08-11,Karuizawa,Nagano,JPN,Japan,172.0,70.0,NaT,68.944559,Kazuaki,Ichimura,Alive
92342,93082,Alfreð Karl Alfreðsson,1964-10-21,NaN,NaN,NaN,Iceland,180.0,78.0,NaT,61.749487,Alfreð,Karl,Alive
74611,75184,Victor Firea,1923-03-16,Mărgineni,Neamț,ROU,Romania,NaN,NaN,2007-05-25,84.191650,Victor,Firea,Died
99733,100532,Andrei Miezin,1974-07-08,Chelyabinsk,Chelyabinsk,RUS,Belarus,180.0,76.0,NaT,52.038330,Andrei,Miezin,Alive
140597,144109,Alice Betto,1987-12-10,Varese,Varese,ITA,Italy,NaN,NaN,NaT,38.614648,Alice,Betto,Alive
18565,18692,Sandie Lister,1961-08-16,Halifax,England,GBR,Great Britain,164.0,62.0,NaT,64.930869,Sandie,Lister,Alive

In [37]:
bios['born_date']=pd.to_datetime(bios['born_date'])
bios['died_date']=pd.to_datetime(bios['died_date'])

In [75]:
bios['age']=np.where(bios['died_date'].isna(),
                     current_date.year-bios['born_date'].dt.year,
                     current_date.year-bios['died_date'].dt.year)

In [81]:
bios[(bios['age']>80) & (bios['status']!='Alive')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,age,first_name,last_name,status
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,96.0,Albert,Canet,Died
9,10,Guy de la Chapelle,1868-07-16,Farges-Allichamps,Cher,FRA,France,NaN,NaN,1923-08-27,103.0,Guy,de,Died
10,11,"Élie, Comte de Lastours",1874-08-12,Orgeval,Yvelines,FRA,France,NaN,NaN,1932-11-18,94.0,"Élie,",Comte,Died
20,21,Pierre Hirsch,1900-11-08,Paris Ie,Paris,FRA,France,NaN,NaN,1942-04-19,84.0,Pierre,Hirsch,Died
24,25,Paul Lecaron,1863-07-29,Neuilly-sur-Seine,Hauts-de-Seine,FRA,France,NaN,NaN,1940-09-17,86.0,Paul,Lecaron,Died
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135269,138432,Daniel Ridgway Knight,1839-03-15,Chambersburg,Pennsylvania,USA,United States,NaN,NaN,1924-03-09,102.0,Daniel,Ridgway,Died
135276,138439,"Louis Dufour, Sr.",1873-01-01,Les Avants,Vaud,SUI,Switzerland,NaN,NaN,1944-04-12,82.0,Louis,"Dufour,",Died
135278,138441,John McEachern,1881-04-29,NaN,NaN,NaN,Canada,NaN,NaN,1939-06-04,87.0,John,McEachern,Died
135281,138444,Louis Renaud,1888-12-06,Buenos Aires,Ciudad Autónoma de Buenos Aires,ARG,France,NaN,NaN,1939-01-01,87.0,Louis,Renaud,Died
135283,138446,Jacques Demaré,1900-09-01,Vincennes,Val-de-Marne,FRA,France,185.0,78.0,1935-12-09,91.0,Jacques,Demaré,Died

In [92]:
bios['height_category']=bios['height_cm'].apply(lambda x : 'short' if x<165 else('Average' if x<185 else 'Tall'))
bios.sample(20)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,age,first_name,last_name,status,height_category
137243,140593,Natalya Diehm,1997-09-23,Gladstone,Queensland,AUS,Australia,175.0,NaN,NaT,29.0,Natalya,Diehm,Alive,Average
36142,36427,Porfirio Reynoso,1950-05-04,NaN,NaN,NaN,Cuba,190.0,85.0,NaT,76.0,Porfirio,Reynoso,Alive,Tall
101642,102560,Charles Brown,1867-03-12,Onarga,Illinois,USA,United States,NaN,NaN,1937-06-07,89.0,Charles,Brown,Died,Tall
130362,133045,Maximilien Van Haaster,1992-06-19,Montréal,Québec,CAN,Canada,185.0,88.0,NaT,34.0,Maximilien,Van,Alive,Tall
107321,108445,Hitoki Iwase,1974-11-10,Nishio,Aichi,JPN,Japan,180.0,74.0,NaT,52.0,Hitoki,Iwase,Alive,Average
109061,110243,Gillian Ferrari,1980-06-23,Thornhill,Ontario,CAN,Canada,173.0,73.0,NaT,46.0,Gillian,Ferrari,Alive,Average
15983,16095,Axel Wilhelm Persson,1888-01-23,Eskilstuna,Södermanland,SWE,Sweden,NaN,NaN,1955-09-02,71.0,Axel,Wilhelm,Died,Tall
119780,121613,Byron Guamá,1985-06-14,San Isidro,Carchi,ECU,Ecuador,165.0,61.0,NaT,41.0,Byron,Guamá,Alive,Average
83237,83895,Gary Battistella,1940-01-13,Trail,British Columbia,CAN,Canada,NaN,NaN,2007-12-12,19.0,Gary,Battistella,Died,Tall
54294,54684,Thio Gim Hock,1938-03-11,NaN,NaN,NaN,Singapore,NaN,NaN,2020-04-03,6.0,Thio,Gim,Died,Tall
49703,50061,Dmitry Sautin,1974-03-15,Voronezh,Voronezh,RUS,Russian Federation Unified Team,172.0,65.0,NaT,52.0,Dmitry,Sautin,Alive,Average
59166,59592,José Inagaki,1965-12-16,NaN,NaN,NaN,Peru,162.0,62.0,NaT,61.0,José,Inagaki,Alive,short
82419,83072,Xi Hongyan,1964-03-17,NaN,NaN,NaN,People's Republic of China,165.0,51.0,NaT,62.0,Xi,Hongyan,Alive,Average
38587,38890,Cornelis Eecen,1898-06-17,Oudkarspel,Noord-Holland,NED,Netherlands,NaN,NaN,1988-12-25,38.0,Cornelis,Eecen,Died,Tall
32915,33163,Estha Essombe,1963-04-20,Boulogne-sur-Mer,Pas-de-Calais,FRA,France,170.0,72.0,NaT,63.0,Estha,Essombe,Alive,Average
124026,126289,Eliane Saholinirina,1982-03-20,Betsihaka,Diana,MAD,Madagascar,154.0,46.0,NaT,44.0,Eliane,Saholinirina,Alive,short
142011,145599,Thom de Boer,1991-12-24,NaN,NaN,NaN,Netherlands,NaN,NaN,NaT,35.0,Thom,de,Alive,Tall
123469,125669,Andrés Mir,1987-01-25,Zaragoza (Saragossa),Zaragoza,ESP,Spain,180.0,75.0,NaT,39.0,Andrés,Mir,Alive,Average
78600,79191,Dudley Wilkins,1914-11-11,Crowley,Louisiana,USA,United States,195.0,84.0,1989-01-01,37.0,Dudley,Wilkins,Died,Tall
51892,52254,Essam Ramadan,1957-11-03,NaN,NaN,NaN,Egypt,179.0,76.0,NaT,69.0,Essam,Ramadan,Alive,Average

In [95]:
def weight(row):
  if row['weight_kg']>80:
    return 'Over Weight'
  else:
    return 'Normal Weight'
bios['weight_category']=bios.apply(weight,axis=1)
bios.sample(18)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,age,first_name,last_name,status,height_category,weight_category
91847,92578,Marco Geisler,1974-01-18,Cottbus,Brandenburg,GER,Germany,201.0,101.0,NaT,52.0,Marco,Geisler,Alive,Tall,Over Weight
90820,91543,Loredana Boboc,1984-05-12,București (Bucharest),București,ROU,Romania,139.0,32.0,NaT,42.0,Loredana,Boboc,Alive,short,Normal Weight
109963,111171,Andréia Rosa,1984-07-08,Araraquara,São Paulo,BRA,Brazil,172.0,63.0,NaT,42.0,Andréia,Rosa,Alive,Average,Normal Weight
32360,32603,Robert Speck,1909-04-28,Sibiu,Sibiu,ROU,Romania,NaN,NaN,1979-07-13,47.0,Robert,Speck,Died,Tall,Normal Weight
31124,31360,Louis Kniep,1876-04-10,NaN,NaN,NaN,United States,NaN,NaN,1967-02-22,59.0,Louis,Kniep,Died,Tall,Normal Weight
36755,37049,Bernard Monnereau,1935-09-18,Tôtes,Seine-Maritime,FRA,France,175.0,72.0,2019-08-24,7.0,Bernard,Monnereau,Died,Average,Normal Weight
8212,8256,Josef Hrubeš,1916-09-26,Slaný,Středočeský kraj,CZE,Czechoslovakia,NaN,NaN,NaT,110.0,Josef,Hrubeš,Alive,Tall,Normal Weight
14147,14240,Alex Ekström,1883-10-04,Enköping,Uppsala,SWE,Sweden,NaN,NaN,1958-02-20,68.0,Alex,Ekström,Died,Tall,Normal Weight
45017,45359,Viki Sölkner,1905-12-08,Graz,Steiermark,AUT,Austria,NaN,NaN,1983-09-28,43.0,Viki,Sölkner,Died,Tall,Normal Weight
60999,61441,Carlos Braniff,1928-01-12,Ciudad de México (Mexico City),Ciudad de México,MEX,Mexico,168.0,62.0,NaT,98.0,Carlos,Braniff,Alive,Average,Normal Weight
120484,122404,Pat Taea,1993-05-25,NaN,NaN,NaN,Cook Islands,170.0,67.0,NaT,33.0,Pat,Taea,Alive,Average,Normal Weight
71996,72541,Yoshitaka Muroya,1930-04-06,NaN,NaN,NaN,Japan,168.0,58.0,2019-03-23,7.0,Yoshitaka,Muroya,Died,Average,Normal Weight
81459,82111,Terry Porter,1953-09-12,Cambridge,Massachusetts,USA,United States,NaN,NaN,NaT,73.0,Terry,Porter,Alive,Tall,Normal Weight
79460,80071,Epameinondas Simiriotis,NaT,NaN,NaN,NaN,Greece,NaN,NaN,NaT,NaN,Epameinondas,Simiriotis,Alive,Tall,Normal Weight
105759,106821,Chiaki Kusuhara,1975-11-01,Matsuyama,Ehime,JPN,Japan,175.0,68.0,NaT,51.0,Chiaki,Kusuhara,Alive,Average,Normal Weight
79762,80402,Percy La Fontaine,1888-01-01,İzmir,İzmir,TUR,Greece,NaN,NaN,1914-08-24,112.0,Percy,La,Died,Tall,Normal Weight
127378,129825,Zurian Hechavarría,1995-08-10,Santiago de Cuba,Santiago de Cuba,CUB,Cuba,164.0,58.0,NaT,31.0,Zurian,Hechavarría,Alive,short,Normal Weight
65750,66247,Bill Smart,1948-06-05,Vancouver,British Columbia,CAN,Canada,177.0,68.0,NaT,78.0,Bill,Smart,Alive,Average,Normal Weight

In [79]:
#save to Data Frame to CSV File
bios.to_csv('/content/drive/MyDrive/Data Sources/olympicsbios.csv',index=False)

In [80]:
bios[(bios['age']>80) & (bios['status']=='Alive')].to_csv('/content/drive/MyDrive/Data Sources/olympicsbios_alive.csv',index=False)

In [82]:
bios[(bios['age']>80) & (bios['status']!='Alive')].to_csv('/content/drive/MyDrive/Data Sources/olympicsbios_died.csv',index=False)

In [85]:
bios[(bios['born_country']=='IND')].to_csv('/content/drive/MyDrive/Data Sources/olympicsbios_india.csv',index=False)

In [86]:
#save to Data Frame to excel File
bios[(bios['born_country']=='IND')].to_excel('/content/drive/MyDrive/Data Sources/olympicsbios_india.xlsx',index=False)

In [88]:
#save to Data Frame to json File
bios[(bios['born_country']=='IND')].to_json('/content/drive/MyDrive/Data Sources/olympicsbios_india.json',index=True)