<a href="https://colab.research.google.com/github/chandupradeep18/Python_pandas/blob/main/Data_Filtering_using_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
sales=pd.read_csv('/content/drive/MyDrive/Data Sources/amazon_sales.csv')
parquet=pd.read_parquet('/content/drive/MyDrive/Data Sources/results.parquet')

In [ ]:
sales.columns #
sales.shape
sales.info()
sales.describe()

In [ ]:
sales.head()
sales.tail()
sales.sample(10)

In [ ]:
sales.loc[9018]
sales.loc[9018,['product_title','product_rating','original_price']]
sales.loc[9018,'product_title']
sales.loc[9018:9324,'product_title']

In [ ]:
sales.iloc[9018]
sales.iloc[9018,[1,2,3,4]]
sales.iloc[9018,2]

np.float64(2740.0)

In [ ]:
print(sales.loc[9018:9100:5,['product_rating','product_category']])
sales.loc[9023,'product_rating']=4.6
print(sales.loc[9018:9100:5,['product_rating','product_category']])
sales.loc[9018:9100:5]

In [ ]:
sales.at[9023,'product_rating']
sales.iat[9023,0]

'AMD Ryzen™ 9 7950X3D 16-Core, 32-Thread Desktop Processor'

In [ ]:
for i in sales.iterrows():
  print(i)
  break

In [ ]:
sales.sort_values(['data_collected_at','product_rating','product_category'],ascending=True)

In [ ]:
#filting Condition
sales.loc[(sales['product_rating']<4.0) & (sales['is_best_seller']=='Best Seller')]
print(parquet.columns)
parquet[(parquet['year'].between(2000,2026)) & (parquet['place'].isin([1,2,3])) & (parquet['type']=='Summer') & (parquet['event'].str.contains('Men')) & (parquet['medal'].isin(['Gold'])) | (parquet['type']=='Winter') & (parquet['event'].str.contains('Women')) & (parquet['medal'].isin(['Gold']))]

Index(['year', 'type', 'discipline', 'event', 'as', 'athlete_id', 'noc',
       'team', 'place', 'tied', 'medal'],
      dtype='object')

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
850,2000.0,Summer,Archery,"Individual, Men (Olympic)",Simon Fairweather,300,AUS,None,1.0,False,Gold
1897,2000.0,Summer,Tennis,"Doubles, Men (Olympic)",Sébastien Lareau,753,CAN,Daniel Nestor,1.0,False,Gold
1904,2000.0,Summer,Tennis,"Doubles, Men (Olympic)",Daniel Nestor,757,CAN,Sébastien Lareau,1.0,False,Gold
2285,2004.0,Summer,Badminton,"Doubles, Men (Olympic)",Ha Tae-Gwon,913,KOR,Kim Dong-Mun,1.0,False,Gold
2295,2004.0,Summer,Badminton,"Doubles, Men (Olympic)",Kim Dong-Mun,916,KOR,Ha Tae-Gwon,1.0,False,Gold
...,...,...,...,...,...,...,...,...,...,...,...
307362,2022.0,Winter,Bobsleigh (Bobsleigh),"Two, Women (Olympic)",Deborah Levi,148384,GER,Laura Nolte,1.0,False,Gold
307868,2022.0,Winter,Short Track Speed Skating (Skating),"3,000 metres Relay, Women (Olympic)",Selma Poutsma,148678,NED,Netherlands,1.0,False,Gold
307873,2022.0,Winter,Short Track Speed Skating (Skating),"3,000 metres Relay, Women (Olympic)",Xandra Velzeboer,148679,NED,Netherlands,1.0,False,Gold
308090,2022.0,Winter,Cross Country Skiing (Skiing),"4 × 5 kilometres Relay, Women (Olympic)",Tatyana Sorina,148775,ROC,ROC,1.0,False,Gold
308092,2022.0,Winter,Cross Country Skiing (Skiing),"4 × 5 kilometres Relay, Women (Olympic)",Veronika Stepanova,148776,ROC,ROC,1.0,False,Gold

In [ ]:
parquet['details']=parquet['type']+" - "+parquet['medal']
parquet.sample(10)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,details
288309,2020.0,Summer,Fencing,"Sabre, Team, Men (Olympic)",Eli Dershwitz,136303,USA,United States,8.0,False,None,NaN
131633,2000.0,Summer,Sailing,"Multihull, Open (Olympic)",Santiago Lange,62704,ARG,Mariano Parada,10.0,False,None,NaN
284911,2016.0,Summer,Golf,"Individual, Men (Olympic)",Alex Čejka,134179,GER,None,21.0,True,None,NaN
211887,1928.0,Winter,Ski Jumping (Skiing),"Large Hill, Individual, Men (Olympic)",Gérard Vuilleumier,98739,SUI,None,30.0,False,None,NaN
54480,1976.0,Summer,Artistic Gymnastics (Gymnastics),"Team All-Around, Women (Olympic)",Rita Peri,28726,ITA,Italy,12.0,False,None,NaN
37622,1924.0,Summer,Fencing,"Foil, Individual, Men (Olympic)",Carlos Guerrico,21061,ARG,None,4.0,False,None,NaN
305382,2020.0,Summer,Karate,"Kata, Women (Olympic)",Dilara Bozan,146922,TUR,None,5.0,True,None,NaN
276486,2016.0,Summer,Hockey,"Hockey, Women (Olympic)",Brooke Peris,129009,AUS,Australia,6.0,False,None,NaN
67285,1948.0,Summer,Artistic Gymnastics (Gymnastics),"Team All-Around, Men (Olympic)",Dionisio Aguilar,30715,MEX,Mexico,16.0,False,None,NaN
99403,1972.0,Summer,Diving (Aquatics),"Platform, Men (Olympic)",Kenneth Sully,46032,CAN,None,29.0,False,None,NaN

In [ ]:
parquet.drop(columns=['details'],inplace=True)
parquet.sample()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
282134,2016.0,Summer,Football (Football),"Football, Men (Olympic)",Santiago Ascacibar,132376,ARG,Argentina,11.0,False,None