<a href="https://colab.research.google.com/github/chandupradeep18/Python_pandas/blob/main/Load_and_access_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

Load data Into Pandas dataFrame From Diffierent Data Sources Like Sql,CSV,EXCEl Etc

In [ ]:
#Loading Data From CSV File Into DataFrame
bio=pd.read_csv('/content/drive/MyDrive/Data Sources/bios.csv')
bio.head()
bio.columns
bio.index
bio.info()
bio.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

          athlete_id      height_cm      weight_kg
count  145500.000000  106651.000000  102070.000000
mean    73686.188955     176.333724      71.890996
std     42868.960158      10.380282      14.465540
min         1.000000     127.000000      25.000000
25%     36663.750000     170.000000      62.000000
50%     73302.500000     176.000000      70.000000
75%    110306.250000     183.000000      80.000000
max    149814.000000     226.000000     198.000000

In [ ]:
#Loading Data From Excel File Into DataFrame
olympics=pd.read_excel('/content/drive/MyDrive/Data Sources/olympics-data.xlsx')
print(bio.columns)
olympics.head()

Index(['athlete_id', 'name', 'born_date', 'born_city', 'born_region',
       'born_country', 'NOC', 'height_cm', 'weight_kg', 'died_date'],
      dtype='object')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [ ]:
#Loading Data From feather File Into DataFrame
feather=pd.read_feather('/content/drive/MyDrive/Data Sources/results.feather')
print(bio.columns)
feather.head()

Index(['athlete_id', 'name', 'born_date', 'born_city', 'born_region',
       'born_country', 'NOC', 'height_cm', 'weight_kg', 'died_date'],
      dtype='object')

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [ ]:
#Loading Data From parquet File Into DataFrame
parquet=pd.read_parquet('/content/drive/MyDrive/Data Sources/results.parquet')
print(parquet.columns)

Index(['year', 'type', 'discipline', 'event', 'as', 'athlete_id', 'noc',
       'team', 'place', 'tied', 'medal'],
      dtype='object')

In [ ]:
parquet.head(10) #Show first 10 row of The Data

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None
5,1996.0,Summer,Tennis,"Singles, Men (Olympic)",Arnaud Boetsch,2,FRA,None,17.0,True,None
6,1996.0,Summer,Tennis,"Doubles, Men (Olympic)",Arnaud Boetsch,2,FRA,Guillaume Raoux,17.0,True,None
7,1924.0,Summer,Tennis,"Singles, Men (Olympic)",Jean Borotra,3,FRA,None,4.0,False,None
8,1924.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean Borotra,3,FRA,Marguerite Billout,15.0,True,None
9,1924.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean Borotra,3,FRA,René Lacoste,3.0,False,Bronze

In [ ]:
parquet.tail(10) #Show last 10 row of the data

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
308398,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Miloš Roman,148978,SVK,Slovakia,3.0,False,Bronze
308399,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Juraj Slafkovský,148979,SVK,Slovakia,3.0,False,Bronze
308400,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Samuel Takáč,148980,SVK,Slovakia,3.0,False,Bronze
308401,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Matej Tomek,148981,SVK,Slovakia,3.0,False,Bronze
308402,2022.0,Winter,Ice Hockey (Ice Hockey),"Ice Hockey, Men (Olympic)",Peter Zuzin,148982,SVK,Slovakia,3.0,False,Bronze
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,None,26.0,False,None
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,None,28.0,False,None
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,None
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,None,NaN,False,None
308407,2022.0,Winter,None,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,None,None,24.0,False,None

In [ ]:
parquet.sample(20) #Show Ramdom 20 Row from The data

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
95163,1964.0,Summer,Shooting,"Rapid-Fire Pistol, 25 metres, Men (Olympic)",Ma Chen-Shan,44461,TPE,None,53.0,False,None
15033,1988.0,Summer,Canoe Sprint (Canoeing),"Kayak Fours, 500 metres, Women (Olympic)",Susie Perrett,9697,GBR,Great Britain,5.0,False,None
42895,1968.0,Summer,Fencing,"Sabre, Team, Men (Olympic)",Cesare Salvadori,22735,ITA,Italy,2.0,False,Silver
197490,2000.0,Summer,Judo,"Middleweight, Women (Olympic)",Yuliya Kuzina,92407,RUS,None,9.0,True,None
140115,1936.0,Summer,Athletics,"200 metres, Men (Olympic)",George Fahoum,67078,EGY,None,4.0,False,None
240697,2008.0,Summer,Football (Football),"Football, Women (Olympic)",Ludmila Manicler,111175,ARG,Argentina,11.0,True,None
29649,1964.0,Summer,Cycling Road (Cycling),"Road Race, Individual, Men (Olympic)",František Řezáč,16282,TCH,None,70.0,False,None
69922,1908.0,Summer,Athletics,"Long Jump, Men (Olympic)",Carl Silfverstrand,31126,SWE,None,20.0,False,None
98294,1980.0,Summer,Swimming (Aquatics),"400 metres Individual Medley, Men (Olympic)",Djan Madruga,45639,BRA,None,5.0,False,None
112102,1984.0,Summer,Swimming (Aquatics),"4 × 100 metres Freestyle Relay, Men (Olympic)",Thomas Lejdström,50427,SWE,Sweden,3.0,False,Bronze
251503,2008.0,Summer,Wrestling,"Middleweight, Freestyle, Men (Olympic)",Augusto Midana,117088,GBS,None,16.0,False,None
215041,2006.0,Winter,Ski Jumping (Skiing),"Large Hill, Team, Men (Olympic)",Choi Heung-Cheol,99855,KOR,Republic of Korea,13.0,False,None
306127,2020.0,Summer,Wrestling,"Middleweight, Freestyle, Men (Olympic)",Kyle Dake,147508,USA,None,3.0,True,Bronze
251485,2012.0,Summer,Wrestling,"Welterweight, Freestyle, Men (Olympic)",Haislan Garcia,117073,CAN,None,7.0,False,None
210738,1948.0,Winter,Bobsleigh (Bobsleigh),"Two, Men (Olympic)",Héctor Tomasi,98304,ARG,Marcelo de Ridder,15.0,False,None
33021,1904.0,Summer,Lacrosse,"Lacrosse, Men (Olympic)",J. W. Dowling,18216,USA,St. Louis Amateur Athletic Association,2.0,False,Silver
171234,1994.0,Winter,Cross Country Skiing (Skiing),"15 kilometres, Women (Olympic)",Nina Kemppel,81466,USA,None,42.0,False,None
287377,2020.0,Summer,Cycling Mountain Bike (Cycling),"Cross-Country, Men (Olympic)",Anton Sintsov,135765,ROC,None,11.0,False,None
85057,1924.0,Summer,Rowing,"Coxless Pairs, Men (Olympic)",Rudolf Bosshard,39700,SUI,Heini Thoma,NaN,False,None
277310,2020.0,Summer,Rowing,"Single Sculls, Women (Olympic)",Carling Zeeman,129491,CAN,None,8.0,False,None

In [ ]:
#loc Locate Data Using Index Value or Values and Select Required Colomn
parquet.loc[9018] #get data using Index Value and You can Select Required Colomn Name or Leave it for all Colomn

year                               1984.0
type                               Summer
discipline        Basketball (Basketball)
event         Basketball, Women (Olympic)
as                    Biljana Majstorović
athlete_id                           5354
noc                                   YUG
team                           Yugoslavia
place                                 6.0
tied                                False
medal                                None
Name: 9018, dtype: object

In [ ]:
parquet.loc[9018,['year','type','athlete_id']]

year          1984.0
type          Summer
athlete_id      5354
Name: 9018, dtype: object

In [ ]:
parquet.loc[3618:5499:10,['year','type','athlete_id']]

        year    type  athlete_id
3618  1976.0  Summer        1810
3628  1984.0  Summer        1819
3638  1988.0  Summer        1827
3648  1976.0  Summer        1833
3658  1924.0  Summer        1841
...      ...     ...         ...
5458  1920.0  Summer        2628
5468  1912.0  Summer        2630
5478  1996.0  Summer        2632
5488  1908.0  Summer        2633
5498  1920.0  Summer        2635

[189 rows x 3 columns]

In [ ]:
#iloc Locate Data Using Index Value or Values and Select Required Colomn using Value not Name
parquet.iloc[9018,3]

'Basketball, Women (Olympic)'

In [ ]:
parquet.iloc[9018,[1,2,3,4,5]]

type                               Summer
discipline        Basketball (Basketball)
event         Basketball, Women (Olympic)
as                    Biljana Majstorović
athlete_id                           5354
Name: 9018, dtype: object

In [ ]:
parquet.iloc[1629:5499,[1,2,3,4,5]]

,type,discipline,event,as,athlete_id
1629,Summer,Tennis,"Doubles, Women (Olympic)",Fernande Arendt,664
1630,Summer,Table Tennis,"Singles, Women (Olympic)",Karina Bogaerts,665
1631,Summer,Tennis,"Doubles, Mixed (Olympic)",Marguerite Chaudoir,666
1632,Summer,Tennis,"Doubles, Women (Olympic)",Marguerite Chaudoir,666
1633,Summer,Tennis,"Singles, Women (Olympic)",Laurence Courtois,667
...,...,...,...,...,...
5494,Summer,Tennis,"Singles, Covered Courts, Men (Olympic)",Gunnar Setterwall,2633
5495,Summer,Tennis,"Doubles, Covered Courts, Men (Olympic)",Gunnar Setterwall,2633
5496,Summer,Tennis,"Singles, Covered Courts, Men (Olympic)",Lennart Silfverstolpe,2634
5497,Summer,Tennis,"Singles, Men (Olympic)",Carl-Eric von Braun,2635
5498,Summer,Tennis,"Doubles, Men (Olympic)",Carl-Eric von Braun,2635

In [ ]:
#using loc we Can Modify data In Data Set
print(parquet.loc[9018])
parquet.loc[9018,'tied']=True
parquet.loc[9018,'medal']='Gold'
print(parquet.loc[9018])
#using iloc we Can Modify data In Data Set
print(parquet.loc[9018])
parquet.loc[9018,9]=False
parquet.loc[9018,10]=None
print(parquet.loc[9018])

year                               1984.0
type                               Summer
discipline        Basketball (Basketball)
event         Basketball, Women (Olympic)
as                    Biljana Majstorović
athlete_id                           5354
noc                                   YUG
team                           Yugoslavia
place                                 6.0
tied                                 True
medal                                Gold
9                                    True
10                                   Gold
Name: 9018, dtype: object
year                               1984.0
type                               Summer
discipline        Basketball (Basketball)
event         Basketball, Women (Olympic)
as                    Biljana Majstorović
athlete_id                           5354
noc                                   YUG
team                           Yugoslavia
place                                 6.0
tied                                 True
medal                                Gold
9                                    True
10                                   Gold
Name: 9018, dtype: object
year                               1984.0
type                               Summer
discipline        Basketball (Basketball)
event         Basketball, Women (Olympic)
as                    Biljana Majstorović
athlete_id                           5354
noc                                   YUG
team                           Yugoslavia
place                                 6.0
tied                                 True
medal                                Gold
9                                    True
10                                   Gold
Name: 9018, dtype: object
year                               1984.0
type                               Summer
discipline        Basketball (Basketball)
event         Basketball, Women (Olympic)
as                    Biljana Majstorović
athlete_id                           5354
noc                                   YUG
team                           Yugoslavia
place                                 6.0
tied                                 True
medal                                Gold
9                                   False
10                                   None
Name: 9018, dtype: object

In [ ]:
parquet.at[9018,'year'] #get Specific Value Using Coloumn Name

np.float64(1984.0)

In [ ]:
parquet.iat[9018,1] #get Specific Value Using Coloumn Value

'Summer'